#!/bin/bash

GO=$(command -v go)

if ! [ -x "$GO" ]; then
	echo 'Error: go is not installed.' >&2
	exit 1
fi

if [ "$#" -ne 1 ]; then
    cat << EOF
Usage: $0 GOPATH
$0 generates a GOPATH and install some useful tools into it.
EOF
	exit 1
fi

GOPATH=$(pwd)/${1}
GOBIN=${GOPATH}/bin

mkdir "$GOPATH"

cat << EOF > "$GOPATH"/env.sh
#!/bin/bash

export GOPATH="${GOPATH}"

export GOBIN="\${GOPATH}/bin"

PATH="\$PATH:\$GOBIN"
EOF

$GO get -u -v github.com/golang/dep/cmd/dep
$GO get -u -v github.com/ramya-rao-a/go-outline
$GO get -u -v github.com/acroca/go-symbols
$GO get -u -v github.com/mdempsky/gocode
$GO get -u -v github.com/rogpeppe/godef
$GO get -u -v golang.org/x/tools/cmd/godoc
$GO get -u -v github.com/zmb3/gogetdoc
$GO get -u -v github.com/golang/lint/golint
$GO get -u -v github.com/fatih/gomodifytags
$GO get -u -v golang.org/x/tools/cmd/gorename
$GO get -u -v sourcegraph.com/sqs/goreturns
$GO get -u -v golang.org/x/tools/cmd/goimports
$GO get -u -v github.com/cweill/gotests/...
$GO get -u -v golang.org/x/tools/cmd/guru
$GO get -u -v github.com/josharian/impl
$GO get -u -v github.com/haya14busa/goplay/cmd/goplay
$GO get -u -v github.com/uudashr/gopkgs/cmd/gopkgs
$GO get -u -v github.com/davidrjenni/reftools/cmd/fillstruct
$GO get -u -v github.com/alecthomas/gometalinter
"${GOBIN}/gometalinter" --install
